spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts:  true
        format_sql: true
        generate_statistics: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: info

hash:
  scheduled: "0 0 3 * * ?"
  hash:
    max-hash-length: 6
    capacity: 10000
    cache:
      fill:
        percent: 20
      solWord: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  redis:
    redis-ttl-minutes: 1440
    prefixes:
      url-prefix: a01.
  app:
    url-name : ${APP_URL_NAME}

locale:
  request:
    name-parameter-in-header: Accept-Language